version: '3'
services:
  my-test3:
    image: python
    build: .
    command: python test.py input.txt
    links:
      - my-postgres
  my-postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - EXPOSE 5433